### ISSUE TITLE
Pass --use-exec to exec-wrappers?

### ISSUE THREAD

**Issue by frabar666** [conda-forge/conda-wrappers-feedstock#11]
exec-wrappers has a `--use-exec` option for non-Windows platforms, added in gqmelo/exec-wrappers#14, so that signals reach the wrapped command.
However this option defaults to false, and conda-wrappers is not passing that argument.

Is there a specific reason for this?
Or would you be OK with a PR adding this argument to `create-wrappers` in `post-link.sh`?

**Comment by gqmelo** [comment]
Hi @frabar666, there is no reason not to use this option. It is just that it was added later and I never updated this feedstock. I'll gladly accept a PR for that :)
