### ISSUE TITLE
Version 1.0.3 Build 1001 is broken

### ISSUE THREAD

**Issue by prusse-martin** [conda-forge/conda-wrappers-feedstock#15]
It's dependency on exec-wrappers is declared as `- exec-wrappers 1.*`  but on linux it uses a feature added in exec-wrappers 1.1.

**Comment by prusse-martin** [comment]
I created #14 to address this feature in conda-wrappers updating it's version and de dependency declaration on exec-wrappers.

**Comment by prusse-martin** [comment]
I guess the steps outlined in [Fixing Broken Packages](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages) to label a build as broken should be taken by a maintainer =)

**Comment by ocefpaf** [comment]
> I guess the steps outlined in [Fixing Broken Packages](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages) to label a build as broken should be taken by a maintainer =)

Nope, the maintainers cannot do it. It should be a conda-forge core member. See the part on the docs that mentions `@conda-forge/core`.

PS: can you list the packages that should be marked as broken?

**Comment by prusse-martin** [comment]
conda-wrappers 1.0.3 build 1001

The steps I mentioned are:

```
To get your package relabeled as broken instead of main, please post on the issue tracker for your feedstock and ping @conda-forge/core with this request:

Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

<insert your reason>
```

**Comment by prusse-martin** [comment]
btw @ocefpaf
Do you actively inspect ALL feedstock issues/PRs? =)
You was faster that the maintainer.

**Comment by ocefpaf** [comment]
> The steps I mentioned are:

Yep. Not the maintainer as it says there :wink:

> You was faster that the maintainer.

Oops. Busted! I'm just a bot.

> conda-wrappers 1.0.3 build 1001

Done. Please check if I got the right ones:

https://anaconda.org/conda-forge/conda-wrappers/files?version=1.0.3

**Comment by prusse-martin** [comment]
Yes, those are the offending builds. Thank you.
