### ISSUE TITLE
How to update existing conda wrappers?

### ISSUE THREAD

**Issue by dakcarto** [conda-forge/conda-wrappers-feedstock#16]
Issue:

What is the preferred method of updating existing `conda` wrappers, i.e. after installing _new_ `conda` packages that provide executables, which you want wrapped as well?

Currently, I am doing this...

```
$ conda install --force-reinstall -c conda-forge conda-wrappers
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/mc3/envs/test

  added / updated specs:
    - conda-wrappers

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: - b'Removing wrappers from /opt/mc3/envs/test/bin/wrappers/conda\n'
| b'Creating wrappers from /opt/mc3/envs/test/bin to /opt/mc3/envs/test/bin/wrappers/conda\n'
done
```

However, that seems a bit heavy-handed. It seems like a simple `envs/myemv/bin/conda-wrappers.sh` script, which does the same ordered steps as `pre-unlink.sh` and `post-link.sh` scripts, would be handy.

Then, a user needs only run `conda-wrappers.sh`. I suppose the script could handle options, such as `-c --create`, `-r --remove`, `-u --update`, then the `pre-unlink.sh` and `post-link.sh` scripts could just leverage it during their operations as well.

Or, am I missing an easier method of doing this? Btw, thanks for the great tool!

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep wrappers
conda-wrappers            1.1.3                    py37_0    conda-forge
exec-wrappers             1.1.3                      py_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : /opt/mc3/envs/test
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.6
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /opt/mc3  (writable)
           channel URLs : https://conda.anaconda.org/osgeo-forge/osx-64
                          https://conda.anaconda.org/osgeo-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/mc3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /opt/mc3/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.6.7 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None

```
</details>

**Comment by ocefpaf** [comment]
This looks like a question about the took and not the package.

Please ask it upstream: https://github.com/gqmelo/exec-wrappers

**Comment by dakcarto** [comment]
@ocefpaf wrote:
> This looks like a question about the took and not the package.

Hi. I see how a feature like updating wrappers would relate to the base tool, but this issue is about this _package_ and how it only calls the underlying tool, with quite specific parameters, during `post-link`.

Clearly, this package could support a simple script to rebuild the wrappers, with those specific tool parameters for `conda`. If I can find the time this week, I will do a PR.

**Comment by gqmelo** [comment]
Hi @dakcarto,

So, the approach of reinstalling the package is normally what I do.
I agree it is probably not the best option, but I just wanted to keep this package as simple as possible.
But I don't see a reason to not create a reusable script that could be called both manually and by the post-link and pre-unlink scripts.
Just be careful to check if conda make the scripts available before the post-link and pre-unlink scripts run.
