### ISSUE TITLE
No Python 3.7 version

### ISSUE THREAD

**Issue by petrushy** [conda-forge/conda-wrappers-feedstock#7]
Current build is not including Python v 3.7 packages.

**Comment by gqmelo** [comment]
Thanks for pointing that out. I tried to open a PR (https://github.com/conda-forge/conda-wrappers-feedstock/pull/8) and request a re-render to add Python 3.7, but the bot is saying there is nothing to re-render.

I have limited internet connectivity right now, but I'll see if I can build on my machine during the week.

**Comment by gqmelo** [comment]
Python 3.7 packages available for all platforms now: https://anaconda.org/conda-forge/conda-wrappers/files?version=1.0.3
